### ISSUE TITLE
Vigrid-deployer-host

### ISSUE THREAD

**Issue by Dilhuidy** [llevier/vigrid#2]
Bonjour M.

Souhaitant mettre en place mon NAS Vigrid, j'ai réalisé l'installation en suivant, premièrement l'installation vigrid1-nas-install.sh puis en utilisant le vigrid1-deployer-install.sh.
Après avoir réglé des soucis de packages (git, grub,...), les deux installations se font sans erreur.
Cependant, ma machine ne connaît pas la commande mentionner à la fin de l'installation qui permet l'ajout d'hôte : vigrid-deployer-host.
Quand est-ce que cette commande est censé être appris par mon PC ?

Cordialement,
Le Bohec Pierre

**Comment by llevier** [comment]
Bonjour Pierre,

La commande 'vigrid-deploy-host' (pas deployer) devrait être dans /Vstorage/GNS3/vigrid/bin-nas/.

L'installation ne modifie pas la variable PATH des fichiers de profile (~/.profile ou /etc/profile), elle laisse cette responsabilité à l'administrateur du NAS. Il suffit sans doute d'ajouter ce chemin dans le path.

Cdlt

**Comment by Dilhuidy** [comment]
Merci je vais essayer de rajouter le path avant d'exécuter le script

**Comment by llevier** [comment]
fermée suite à inactivité
